name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/checkout@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          NEXT_PUBLIC_API_BASE_URL: "https://ignite-devstore-api.vercel.app"
          APP_URL: "http://localhost:3000"
        with:
          build: npm run build
          start: npm start
